# Generated by Django 5.2.1 on 2025-07-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0002_alter_member_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilization',
            name='category',
            field=models.CharField(choices=[('yoga', 'Yoga'), ('fitness', 'Fitness'), ('workshop', 'Workshop')], default='fitness', max_length=50),
        ),
    ]
